// source: dapr/proto/sentry/v1/sentry.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.dapr.proto.sentry.v1.SignCertificateRequest', null, global);
goog.exportSymbol('proto.dapr.proto.sentry.v1.SignCertificateRequest.TokenValidator', null, global);
goog.exportSymbol('proto.dapr.proto.sentry.v1.SignCertificateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.sentry.v1.SignCertificateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.sentry.v1.SignCertificateRequest.displayName = 'proto.dapr.proto.sentry.v1.SignCertificateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dapr.proto.sentry.v1.SignCertificateResponse.repeatedFields_, null);
};
goog.inherits(proto.dapr.proto.sentry.v1.SignCertificateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.sentry.v1.SignCertificateResponse.displayName = 'proto.dapr.proto.sentry.v1.SignCertificateResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.sentry.v1.SignCertificateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.sentry.v1.SignCertificateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    token: jspb.Message.getFieldWithDefault(msg, 2, ""),
    trustDomain: jspb.Message.getFieldWithDefault(msg, 3, ""),
    namespace: jspb.Message.getFieldWithDefault(msg, 4, ""),
    certificateSigningRequest: msg.getCertificateSigningRequest_asB64(),
    tokenValidator: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateRequest}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.sentry.v1.SignCertificateRequest;
  return proto.dapr.proto.sentry.v1.SignCertificateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.sentry.v1.SignCertificateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateRequest}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrustDomain(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamespace(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCertificateSigningRequest(value);
      break;
    case 6:
      var value = /** @type {!proto.dapr.proto.sentry.v1.SignCertificateRequest.TokenValidator} */ (reader.readEnum());
      msg.setTokenValidator(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.sentry.v1.SignCertificateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.sentry.v1.SignCertificateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTrustDomain();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNamespace();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCertificateSigningRequest_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getTokenValidator();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.TokenValidator = {
  UNKNOWN: 0,
  INSECURE: 1,
  KUBERNETES: 2,
  JWKS: 3
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateRequest} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string token = 2;
 * @return {string}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateRequest} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.setToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string trust_domain = 3;
 * @return {string}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.getTrustDomain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateRequest} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.setTrustDomain = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string namespace = 4;
 * @return {string}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.getNamespace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateRequest} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.setNamespace = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bytes certificate_signing_request = 5;
 * @return {!(string|Uint8Array)}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.getCertificateSigningRequest = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes certificate_signing_request = 5;
 * This is a type-conversion wrapper around `getCertificateSigningRequest()`
 * @return {string}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.getCertificateSigningRequest_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCertificateSigningRequest()));
};


/**
 * optional bytes certificate_signing_request = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCertificateSigningRequest()`
 * @return {!Uint8Array}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.getCertificateSigningRequest_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCertificateSigningRequest()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateRequest} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.setCertificateSigningRequest = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional TokenValidator token_validator = 6;
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateRequest.TokenValidator}
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.getTokenValidator = function() {
  return /** @type {!proto.dapr.proto.sentry.v1.SignCertificateRequest.TokenValidator} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.dapr.proto.sentry.v1.SignCertificateRequest.TokenValidator} value
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateRequest} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateRequest.prototype.setTokenValidator = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.sentry.v1.SignCertificateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.sentry.v1.SignCertificateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    workloadCertificate: msg.getWorkloadCertificate_asB64(),
    trustChainCertificatesList: msg.getTrustChainCertificatesList_asB64(),
    validUntil: (f = msg.getValidUntil()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateResponse}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.sentry.v1.SignCertificateResponse;
  return proto.dapr.proto.sentry.v1.SignCertificateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.sentry.v1.SignCertificateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateResponse}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setWorkloadCertificate(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addTrustChainCertificates(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setValidUntil(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.sentry.v1.SignCertificateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.sentry.v1.SignCertificateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorkloadCertificate_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getTrustChainCertificatesList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      2,
      f
    );
  }
  f = message.getValidUntil();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes workload_certificate = 1;
 * @return {!(string|Uint8Array)}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.getWorkloadCertificate = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes workload_certificate = 1;
 * This is a type-conversion wrapper around `getWorkloadCertificate()`
 * @return {string}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.getWorkloadCertificate_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getWorkloadCertificate()));
};


/**
 * optional bytes workload_certificate = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getWorkloadCertificate()`
 * @return {!Uint8Array}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.getWorkloadCertificate_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getWorkloadCertificate()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateResponse} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.setWorkloadCertificate = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * repeated bytes trust_chain_certificates = 2;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.getTrustChainCertificatesList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * repeated bytes trust_chain_certificates = 2;
 * This is a type-conversion wrapper around `getTrustChainCertificatesList()`
 * @return {!Array<string>}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.getTrustChainCertificatesList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getTrustChainCertificatesList()));
};


/**
 * repeated bytes trust_chain_certificates = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getTrustChainCertificatesList()`
 * @return {!Array<!Uint8Array>}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.getTrustChainCertificatesList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getTrustChainCertificatesList()));
};


/**
 * @param {!(Array<!Uint8Array>|Array<string>)} value
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateResponse} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.setTrustChainCertificatesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateResponse} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.addTrustChainCertificates = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateResponse} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.clearTrustChainCertificatesList = function() {
  return this.setTrustChainCertificatesList([]);
};


/**
 * optional google.protobuf.Timestamp valid_until = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.getValidUntil = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateResponse} returns this
*/
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.setValidUntil = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.sentry.v1.SignCertificateResponse} returns this
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.clearValidUntil = function() {
  return this.setValidUntil(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.sentry.v1.SignCertificateResponse.prototype.hasValidUntil = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.dapr.proto.sentry.v1);
