//
//Copyright 2026 The Dapr Authors
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file dapr/proto/durabletask/v1/attestation.proto (syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file dapr/proto/durabletask/v1/attestation.proto.
 */
export const file_dapr_proto_durabletask_v1_attestation = /*@__PURE__*/
  fileDesc("CitkYXByL3Byb3RvL2R1cmFibGV0YXNrL3YxL2F0dGVzdGF0aW9uLnByb3RvIs8BCiFDaGlsZENvbXBsZXRpb25BdHRlc3RhdGlvblBheWxvYWQSGAoQcGFyZW50SW5zdGFuY2VJZBgBIAEoCRIdChVwYXJlbnRUYXNrU2NoZWR1bGVkSWQYAiABKAUSEAoIaW9EaWdlc3QYAyABKAwSGAoQc2lnbmVyQ2VydERpZ2VzdBgEIAEoDBInCg50ZXJtaW5hbFN0YXR1cxgFIAEoDjIPLlRlcm1pbmFsU3RhdHVzEhwKFGNhbm9uaWNhbFNwZWNWZXJzaW9uGAYgASgNIkAKGkNoaWxkQ29tcGxldGlvbkF0dGVzdGF0aW9uEg8KB3BheWxvYWQYASABKAwSEQoJc2lnbmF0dXJlGAIgASgMIvABCiRBY3Rpdml0eUNvbXBsZXRpb25BdHRlc3RhdGlvblBheWxvYWQSGAoQcGFyZW50SW5zdGFuY2VJZBgBIAEoCRIdChVwYXJlbnRUYXNrU2NoZWR1bGVkSWQYAiABKAUSFAoMYWN0aXZpdHlOYW1lGAMgASgJEhAKCGlvRGlnZXN0GAQgASgMEhgKEHNpZ25lckNlcnREaWdlc3QYBSABKAwSLwoOdGVybWluYWxTdGF0dXMYBiABKA4yFy5BY3Rpdml0eVRlcm1pbmFsU3RhdHVzEhwKFGNhbm9uaWNhbFNwZWNWZXJzaW9uGAcgASgNIkMKHUFjdGl2aXR5Q29tcGxldGlvbkF0dGVzdGF0aW9uEg8KB3BheWxvYWQYASABKAwSEQoJc2lnbmF0dXJlGAIgASgMIkEKGkV4dGVybmFsU2lnbmluZ0NlcnRpZmljYXRlEg4KBmRpZ2VzdBgBIAEoDBITCgtjZXJ0aWZpY2F0ZRgCIAEoDCpsCg5UZXJtaW5hbFN0YXR1cxIfChtURVJNSU5BTF9TVEFUVVNfVU5TUEVDSUZJRUQQABIdChlURVJNSU5BTF9TVEFUVVNfQ09NUExFVEVEEAESGgoWVEVSTUlOQUxfU1RBVFVTX0ZBSUxFRBACKo8BChZBY3Rpdml0eVRlcm1pbmFsU3RhdHVzEigKJEFDVElWSVRZX1RFUk1JTkFMX1NUQVRVU19VTlNQRUNJRklFRBAAEiYKIkFDVElWSVRZX1RFUk1JTkFMX1NUQVRVU19DT01QTEVURUQQARIjCh9BQ1RJVklUWV9URVJNSU5BTF9TVEFUVVNfRkFJTEVEEAJCagoraW8uZGFwci5kdXJhYmxldGFzay5pbXBsZW1lbnRhdGlvbi5wcm90b2J1ZkIQQXR0ZXN0YXRpb25Qcm90b1ABWgsvYXBpL3Byb3Rvc6oCGURhcHIuRHVyYWJsZVRhc2suUHJvdG9idWZiBnByb3RvMw");

/**
 * Describes the message ChildCompletionAttestationPayload.
 * Use `create(ChildCompletionAttestationPayloadSchema)` to create a new message.
 */
export const ChildCompletionAttestationPayloadSchema = /*@__PURE__*/
  messageDesc(file_dapr_proto_durabletask_v1_attestation, 0);

/**
 * Describes the message ChildCompletionAttestation.
 * Use `create(ChildCompletionAttestationSchema)` to create a new message.
 */
export const ChildCompletionAttestationSchema = /*@__PURE__*/
  messageDesc(file_dapr_proto_durabletask_v1_attestation, 1);

/**
 * Describes the message ActivityCompletionAttestationPayload.
 * Use `create(ActivityCompletionAttestationPayloadSchema)` to create a new message.
 */
export const ActivityCompletionAttestationPayloadSchema = /*@__PURE__*/
  messageDesc(file_dapr_proto_durabletask_v1_attestation, 2);

/**
 * Describes the message ActivityCompletionAttestation.
 * Use `create(ActivityCompletionAttestationSchema)` to create a new message.
 */
export const ActivityCompletionAttestationSchema = /*@__PURE__*/
  messageDesc(file_dapr_proto_durabletask_v1_attestation, 3);

/**
 * Describes the message ExternalSigningCertificate.
 * Use `create(ExternalSigningCertificateSchema)` to create a new message.
 */
export const ExternalSigningCertificateSchema = /*@__PURE__*/
  messageDesc(file_dapr_proto_durabletask_v1_attestation, 4);

/**
 * Describes the enum TerminalStatus.
 */
export const TerminalStatusSchema = /*@__PURE__*/
  enumDesc(file_dapr_proto_durabletask_v1_attestation, 0);

/**
 * Terminal state of a child workflow at the moment of attestation.
 *
 * @generated from enum TerminalStatus
 */
export const TerminalStatus = /*@__PURE__*/
  tsEnum(TerminalStatusSchema);

/**
 * Describes the enum ActivityTerminalStatus.
 */
export const ActivityTerminalStatusSchema = /*@__PURE__*/
  enumDesc(file_dapr_proto_durabletask_v1_attestation, 1);

/**
 * Terminal state of an activity task at the moment of attestation.
 * Activities have no "terminate" operation, so the space is smaller than
 * TerminalStatus.
 *
 * @generated from enum ActivityTerminalStatus
 */
export const ActivityTerminalStatus = /*@__PURE__*/
  tsEnum(ActivityTerminalStatusSchema);

