// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file dapr/proto/durabletask/v1/history_events.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { HistoryPropagationScope, OrchestrationStatus, ParentInstanceInfo, RerunParentInstanceInfo, RetryParentInstanceInfo, StalledReason, TaskFailureDetails, TaskRouter, TraceContext, WorkflowInstance, WorkflowVersion } from "./orchestration_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { ActivityCompletionAttestation, ChildCompletionAttestation } from "./attestation_pb.js";

/**
 * Describes the file dapr/proto/durabletask/v1/history_events.proto.
 */
export declare const file_dapr_proto_durabletask_v1_history_events: GenFile;

/**
 * @generated from message ExecutionStartedEvent
 */
export declare type ExecutionStartedEvent = Message<"ExecutionStartedEvent"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.StringValue version = 2;
   */
  version?: string | undefined;

  /**
   * @generated from field: google.protobuf.StringValue input = 3;
   */
  input?: string | undefined;

  /**
   * @generated from field: WorkflowInstance workflowInstance = 4;
   */
  workflowInstance?: WorkflowInstance | undefined;

  /**
   * @generated from field: ParentInstanceInfo parentInstance = 5;
   */
  parentInstance?: ParentInstanceInfo | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp scheduledStartTimestamp = 6;
   */
  scheduledStartTimestamp?: Timestamp | undefined;

  /**
   * @generated from field: TraceContext parentTraceContext = 7;
   */
  parentTraceContext?: TraceContext | undefined;

  /**
   * @generated from field: google.protobuf.StringValue workflowSpanID = 8;
   */
  workflowSpanID?: string | undefined;

  /**
   * @generated from field: map<string, string> tags = 9;
   */
  tags: { [key: string]: string };
};

/**
 * Describes the message ExecutionStartedEvent.
 * Use `create(ExecutionStartedEventSchema)` to create a new message.
 */
export declare const ExecutionStartedEventSchema: GenMessage<ExecutionStartedEvent>;

/**
 * @generated from message ExecutionCompletedEvent
 */
export declare type ExecutionCompletedEvent = Message<"ExecutionCompletedEvent"> & {
  /**
   * @generated from field: OrchestrationStatus workflowStatus = 1;
   */
  workflowStatus: OrchestrationStatus;

  /**
   * @generated from field: google.protobuf.StringValue result = 2;
   */
  result?: string | undefined;

  /**
   * @generated from field: TaskFailureDetails failureDetails = 3;
   */
  failureDetails?: TaskFailureDetails | undefined;
};

/**
 * Describes the message ExecutionCompletedEvent.
 * Use `create(ExecutionCompletedEventSchema)` to create a new message.
 */
export declare const ExecutionCompletedEventSchema: GenMessage<ExecutionCompletedEvent>;

/**
 * @generated from message ExecutionTerminatedEvent
 */
export declare type ExecutionTerminatedEvent = Message<"ExecutionTerminatedEvent"> & {
  /**
   * @generated from field: google.protobuf.StringValue input = 1;
   */
  input?: string | undefined;

  /**
   * @generated from field: bool recurse = 2;
   */
  recurse: boolean;
};

/**
 * Describes the message ExecutionTerminatedEvent.
 * Use `create(ExecutionTerminatedEventSchema)` to create a new message.
 */
export declare const ExecutionTerminatedEventSchema: GenMessage<ExecutionTerminatedEvent>;

/**
 * @generated from message TaskScheduledEvent
 */
export declare type TaskScheduledEvent = Message<"TaskScheduledEvent"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.StringValue version = 2;
   */
  version?: string | undefined;

  /**
   * @generated from field: google.protobuf.StringValue input = 3;
   */
  input?: string | undefined;

  /**
   * @generated from field: TraceContext parentTraceContext = 4;
   */
  parentTraceContext?: TraceContext | undefined;

  /**
   * @generated from field: string taskExecutionId = 5;
   */
  taskExecutionId: string;

  /**
   * If defined, indicates that this task was the starting point of a new
   * workflow execution as the result of a rerun operation.
   *
   * @generated from field: optional RerunParentInstanceInfo rerunParentInstanceInfo = 6;
   */
  rerunParentInstanceInfo?: RerunParentInstanceInfo | undefined;

  /**
   * History propagation scope used when this task was originally scheduled.
   * Persisted on the event so rerun can re-issue the task with the same
   * scope after the action has been discarded.
   *
   * @generated from field: optional HistoryPropagationScope historyPropagationScope = 7;
   */
  historyPropagationScope?: HistoryPropagationScope | undefined;
};

/**
 * Describes the message TaskScheduledEvent.
 * Use `create(TaskScheduledEventSchema)` to create a new message.
 */
export declare const TaskScheduledEventSchema: GenMessage<TaskScheduledEvent>;

/**
 * @generated from message TaskCompletedEvent
 */
export declare type TaskCompletedEvent = Message<"TaskCompletedEvent"> & {
  /**
   * @generated from field: int32 taskScheduledId = 1;
   */
  taskScheduledId: number;

  /**
   * @generated from field: google.protobuf.StringValue result = 2;
   */
  result?: string | undefined;

  /**
   * @generated from field: string taskExecutionId = 3;
   */
  taskExecutionId: string;

  /**
   * Attestation signed by the activity executor's SPIFFE identity.
   * Present when the activity was executed under a signing-enabled
   * configuration. Verified on inbox ingestion against the companion
   * signerCertificate and preserved in stored history for future audit
   * and forwarding via provenance bundles.
   *
   * @generated from field: optional ActivityCompletionAttestation attestation = 4;
   */
  attestation?: ActivityCompletionAttestation | undefined;

  /**
   * Companion: DER-encoded X.509 certificate chain of the executor's
   * signing identity (leaf first, intermediates concatenated; same
   * format as SigningCertificate.certificate in backend_service.proto).
   * Wire-only; stripped by the receiver before the event is written to
   * history-NNNNNN. The certificate lives once in ext-sigcert-NNNNNN,
   * referenced by attestation payload's signerCertDigest.
   *
   * @generated from field: optional bytes signerCertificate = 5;
   */
  signerCertificate?: Uint8Array | undefined;
};

/**
 * Describes the message TaskCompletedEvent.
 * Use `create(TaskCompletedEventSchema)` to create a new message.
 */
export declare const TaskCompletedEventSchema: GenMessage<TaskCompletedEvent>;

/**
 * @generated from message TaskFailedEvent
 */
export declare type TaskFailedEvent = Message<"TaskFailedEvent"> & {
  /**
   * @generated from field: int32 taskScheduledId = 1;
   */
  taskScheduledId: number;

  /**
   * @generated from field: TaskFailureDetails failureDetails = 2;
   */
  failureDetails?: TaskFailureDetails | undefined;

  /**
   * @generated from field: string taskExecutionId = 3;
   */
  taskExecutionId: string;

  /**
   * See TaskCompletedEvent.attestation.
   *
   * @generated from field: optional ActivityCompletionAttestation attestation = 4;
   */
  attestation?: ActivityCompletionAttestation | undefined;

  /**
   * Wire-only companion; see TaskCompletedEvent.signerCertificate.
   *
   * @generated from field: optional bytes signerCertificate = 5;
   */
  signerCertificate?: Uint8Array | undefined;
};

/**
 * Describes the message TaskFailedEvent.
 * Use `create(TaskFailedEventSchema)` to create a new message.
 */
export declare const TaskFailedEventSchema: GenMessage<TaskFailedEvent>;

/**
 * @generated from message ChildWorkflowInstanceCreatedEvent
 */
export declare type ChildWorkflowInstanceCreatedEvent = Message<"ChildWorkflowInstanceCreatedEvent"> & {
  /**
   * @generated from field: string instanceId = 1;
   */
  instanceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.StringValue version = 3;
   */
  version?: string | undefined;

  /**
   * @generated from field: google.protobuf.StringValue input = 4;
   */
  input?: string | undefined;

  /**
   * @generated from field: TraceContext parentTraceContext = 5;
   */
  parentTraceContext?: TraceContext | undefined;

  /**
   * If defined, indicates that this task was the starting point of a new
   * workflow execution as the result of a rerun operation.
   *
   * @generated from field: optional RerunParentInstanceInfo rerunParentInstanceInfo = 6;
   */
  rerunParentInstanceInfo?: RerunParentInstanceInfo | undefined;

  /**
   * History propagation scope used when this child workflow was originally
   * scheduled. Persisted on the event so rerun can re-issue the child with
   * the same scope after the action has been discarded.
   *
   * @generated from field: optional HistoryPropagationScope historyPropagationScope = 7;
   */
  historyPropagationScope?: HistoryPropagationScope | undefined;

  /**
   * If defined, indicates that this child workflow is a retry attempt and
   * links it back to the first attempt in the retry chain. Absent on the
   * first attempt. Consumers correlate retry attempts by grouping on
   * retryParentInstanceInfo.instanceID when present, otherwise on this
   * event's own instanceId.
   *
   * @generated from field: optional RetryParentInstanceInfo retryParentInstanceInfo = 8;
   */
  retryParentInstanceInfo?: RetryParentInstanceInfo | undefined;
};

/**
 * Describes the message ChildWorkflowInstanceCreatedEvent.
 * Use `create(ChildWorkflowInstanceCreatedEventSchema)` to create a new message.
 */
export declare const ChildWorkflowInstanceCreatedEventSchema: GenMessage<ChildWorkflowInstanceCreatedEvent>;

/**
 * @generated from message ChildWorkflowInstanceCompletedEvent
 */
export declare type ChildWorkflowInstanceCompletedEvent = Message<"ChildWorkflowInstanceCompletedEvent"> & {
  /**
   * @generated from field: int32 taskScheduledId = 1;
   */
  taskScheduledId: number;

  /**
   * @generated from field: google.protobuf.StringValue result = 2;
   */
  result?: string | undefined;

  /**
   * Attestation signed by the completing child workflow's SPIFFE
   * identity. Present when the child was executed under a signing-enabled
   * configuration. Verified on inbox ingestion against the companion
   * signerCertificate and preserved in stored history for future audit
   * and forwarding via provenance bundles.
   *
   * @generated from field: optional ChildCompletionAttestation attestation = 3;
   */
  attestation?: ChildCompletionAttestation | undefined;

  /**
   * Companion: DER-encoded X.509 certificate chain of the child's signing
   * identity (leaf first, intermediates concatenated; same format as
   * backend_service.proto: SigningCertificate.certificate). Wire-only;
   * stripped by the receiver before the event is written to
   * history-NNNNNN. The certificate lives once in ext-sigcert-NNNNNN,
   * referenced by attestation payload's signerCertDigest.
   *
   * @generated from field: optional bytes signerCertificate = 4;
   */
  signerCertificate?: Uint8Array | undefined;
};

/**
 * Describes the message ChildWorkflowInstanceCompletedEvent.
 * Use `create(ChildWorkflowInstanceCompletedEventSchema)` to create a new message.
 */
export declare const ChildWorkflowInstanceCompletedEventSchema: GenMessage<ChildWorkflowInstanceCompletedEvent>;

/**
 * @generated from message ChildWorkflowInstanceFailedEvent
 */
export declare type ChildWorkflowInstanceFailedEvent = Message<"ChildWorkflowInstanceFailedEvent"> & {
  /**
   * @generated from field: int32 taskScheduledId = 1;
   */
  taskScheduledId: number;

  /**
   * @generated from field: TaskFailureDetails failureDetails = 2;
   */
  failureDetails?: TaskFailureDetails | undefined;

  /**
   * See ChildWorkflowInstanceCompletedEvent.attestation.
   *
   * @generated from field: optional ChildCompletionAttestation attestation = 3;
   */
  attestation?: ChildCompletionAttestation | undefined;

  /**
   * Wire-only companion; see
   * ChildWorkflowInstanceCompletedEvent.signerCertificate.
   *
   * @generated from field: optional bytes signerCertificate = 4;
   */
  signerCertificate?: Uint8Array | undefined;
};

/**
 * Describes the message ChildWorkflowInstanceFailedEvent.
 * Use `create(ChildWorkflowInstanceFailedEventSchema)` to create a new message.
 */
export declare const ChildWorkflowInstanceFailedEventSchema: GenMessage<ChildWorkflowInstanceFailedEvent>;

/**
 * DetachedWorkflowInstanceCreatedEvent records that a running workflow
 * created a new, detached workflow instance via CreateDetachedWorkflowAction.
 * The new workflow has no parent linkage (no completion or failure flows
 * back), so this event only stores a pointer to the spawned instance — the
 * inputs themselves are consumed directly from the action when scheduling.
 * Replay matches on instanceId, so it is the same value the action carried.
 *
 * @generated from message DetachedWorkflowInstanceCreatedEvent
 */
export declare type DetachedWorkflowInstanceCreatedEvent = Message<"DetachedWorkflowInstanceCreatedEvent"> & {
  /**
   * @generated from field: string instanceId = 1;
   */
  instanceId: string;
};

/**
 * Describes the message DetachedWorkflowInstanceCreatedEvent.
 * Use `create(DetachedWorkflowInstanceCreatedEventSchema)` to create a new message.
 */
export declare const DetachedWorkflowInstanceCreatedEventSchema: GenMessage<DetachedWorkflowInstanceCreatedEvent>;

/**
 * Indicates the timer was created by a createTimer call with no special origin.
 *
 * @generated from message TimerOriginCreateTimer
 */
export declare type TimerOriginCreateTimer = Message<"TimerOriginCreateTimer"> & {
};

/**
 * Describes the message TimerOriginCreateTimer.
 * Use `create(TimerOriginCreateTimerSchema)` to create a new message.
 */
export declare const TimerOriginCreateTimerSchema: GenMessage<TimerOriginCreateTimer>;

/**
 * Indicates the timer was created as a timeout for a waitForExternalEvent call.
 *
 * @generated from message TimerOriginExternalEvent
 */
export declare type TimerOriginExternalEvent = Message<"TimerOriginExternalEvent"> & {
  /**
   * The name of the external event being waited on, matching EventRaisedEvent.name.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message TimerOriginExternalEvent.
 * Use `create(TimerOriginExternalEventSchema)` to create a new message.
 */
export declare const TimerOriginExternalEventSchema: GenMessage<TimerOriginExternalEvent>;

/**
 * Indicates the timer was created as a retry delay for an activity execution.
 *
 * @generated from message TimerOriginActivityRetry
 */
export declare type TimerOriginActivityRetry = Message<"TimerOriginActivityRetry"> & {
  /**
   * The task execution ID of the activity being retried.
   *
   * @generated from field: string taskExecutionId = 1;
   */
  taskExecutionId: string;
};

/**
 * Describes the message TimerOriginActivityRetry.
 * Use `create(TimerOriginActivityRetrySchema)` to create a new message.
 */
export declare const TimerOriginActivityRetrySchema: GenMessage<TimerOriginActivityRetry>;

/**
 * Indicates the timer was created as a retry delay for a child workflow execution.
 *
 * @generated from message TimerOriginChildWorkflowRetry
 */
export declare type TimerOriginChildWorkflowRetry = Message<"TimerOriginChildWorkflowRetry"> & {
  /**
   * The instance ID of the workflow being retried.
   *
   * @generated from field: string instanceId = 1;
   */
  instanceId: string;
};

/**
 * Describes the message TimerOriginChildWorkflowRetry.
 * Use `create(TimerOriginChildWorkflowRetrySchema)` to create a new message.
 */
export declare const TimerOriginChildWorkflowRetrySchema: GenMessage<TimerOriginChildWorkflowRetry>;

/**
 * @generated from message TimerCreatedEvent
 */
export declare type TimerCreatedEvent = Message<"TimerCreatedEvent"> & {
  /**
   * @generated from field: google.protobuf.Timestamp fireAt = 1;
   */
  fireAt?: Timestamp | undefined;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;

  /**
   * If defined, indicates that this task was the starting point of a new
   * workflow execution as the result of a rerun operation.
   *
   * @generated from field: optional RerunParentInstanceInfo rerunParentInstanceInfo = 3;
   */
  rerunParentInstanceInfo?: RerunParentInstanceInfo | undefined;

  /**
   * If set, provides additional context attached to this timer.
   *
   * @generated from oneof TimerCreatedEvent.origin
   */
  origin: {
    /**
     * @generated from field: TimerOriginCreateTimer createTimer = 4;
     */
    value: TimerOriginCreateTimer;
    case: "createTimer";
  } | {
    /**
     * @generated from field: TimerOriginExternalEvent externalEvent = 5;
     */
    value: TimerOriginExternalEvent;
    case: "externalEvent";
  } | {
    /**
     * @generated from field: TimerOriginActivityRetry activityRetry = 6;
     */
    value: TimerOriginActivityRetry;
    case: "activityRetry";
  } | {
    /**
     * @generated from field: TimerOriginChildWorkflowRetry childWorkflowRetry = 7;
     */
    value: TimerOriginChildWorkflowRetry;
    case: "childWorkflowRetry";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message TimerCreatedEvent.
 * Use `create(TimerCreatedEventSchema)` to create a new message.
 */
export declare const TimerCreatedEventSchema: GenMessage<TimerCreatedEvent>;

/**
 * @generated from message TimerFiredEvent
 */
export declare type TimerFiredEvent = Message<"TimerFiredEvent"> & {
  /**
   * @generated from field: google.protobuf.Timestamp fireAt = 1;
   */
  fireAt?: Timestamp | undefined;

  /**
   * @generated from field: int32 timerId = 2;
   */
  timerId: number;
};

/**
 * Describes the message TimerFiredEvent.
 * Use `create(TimerFiredEventSchema)` to create a new message.
 */
export declare const TimerFiredEventSchema: GenMessage<TimerFiredEvent>;

/**
 * @generated from message WorkflowStartedEvent
 */
export declare type WorkflowStartedEvent = Message<"WorkflowStartedEvent"> & {
  /**
   * @generated from field: optional WorkflowVersion version = 1;
   */
  version?: WorkflowVersion | undefined;
};

/**
 * Describes the message WorkflowStartedEvent.
 * Use `create(WorkflowStartedEventSchema)` to create a new message.
 */
export declare const WorkflowStartedEventSchema: GenMessage<WorkflowStartedEvent>;

/**
 * No payload data
 *
 * @generated from message WorkflowCompletedEvent
 */
export declare type WorkflowCompletedEvent = Message<"WorkflowCompletedEvent"> & {
};

/**
 * Describes the message WorkflowCompletedEvent.
 * Use `create(WorkflowCompletedEventSchema)` to create a new message.
 */
export declare const WorkflowCompletedEventSchema: GenMessage<WorkflowCompletedEvent>;

/**
 * @generated from message EventSentEvent
 */
export declare type EventSentEvent = Message<"EventSentEvent"> & {
  /**
   * @generated from field: string instanceId = 1;
   */
  instanceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.StringValue input = 3;
   */
  input?: string | undefined;
};

/**
 * Describes the message EventSentEvent.
 * Use `create(EventSentEventSchema)` to create a new message.
 */
export declare const EventSentEventSchema: GenMessage<EventSentEvent>;

/**
 * @generated from message EventRaisedEvent
 */
export declare type EventRaisedEvent = Message<"EventRaisedEvent"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.StringValue input = 2;
   */
  input?: string | undefined;
};

/**
 * Describes the message EventRaisedEvent.
 * Use `create(EventRaisedEventSchema)` to create a new message.
 */
export declare const EventRaisedEventSchema: GenMessage<EventRaisedEvent>;

/**
 * @generated from message ContinueAsNewEvent
 */
export declare type ContinueAsNewEvent = Message<"ContinueAsNewEvent"> & {
  /**
   * @generated from field: google.protobuf.StringValue input = 1;
   */
  input?: string | undefined;
};

/**
 * Describes the message ContinueAsNewEvent.
 * Use `create(ContinueAsNewEventSchema)` to create a new message.
 */
export declare const ContinueAsNewEventSchema: GenMessage<ContinueAsNewEvent>;

/**
 * @generated from message ExecutionSuspendedEvent
 */
export declare type ExecutionSuspendedEvent = Message<"ExecutionSuspendedEvent"> & {
  /**
   * @generated from field: google.protobuf.StringValue input = 1;
   */
  input?: string | undefined;
};

/**
 * Describes the message ExecutionSuspendedEvent.
 * Use `create(ExecutionSuspendedEventSchema)` to create a new message.
 */
export declare const ExecutionSuspendedEventSchema: GenMessage<ExecutionSuspendedEvent>;

/**
 * @generated from message ExecutionResumedEvent
 */
export declare type ExecutionResumedEvent = Message<"ExecutionResumedEvent"> & {
  /**
   * @generated from field: google.protobuf.StringValue input = 1;
   */
  input?: string | undefined;
};

/**
 * Describes the message ExecutionResumedEvent.
 * Use `create(ExecutionResumedEventSchema)` to create a new message.
 */
export declare const ExecutionResumedEventSchema: GenMessage<ExecutionResumedEvent>;

/**
 * @generated from message ExecutionStalledEvent
 */
export declare type ExecutionStalledEvent = Message<"ExecutionStalledEvent"> & {
  /**
   * @generated from field: StalledReason reason = 1;
   */
  reason: StalledReason;

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string | undefined;
};

/**
 * Describes the message ExecutionStalledEvent.
 * Use `create(ExecutionStalledEventSchema)` to create a new message.
 */
export declare const ExecutionStalledEventSchema: GenMessage<ExecutionStalledEvent>;

/**
 * @generated from message HistoryEvent
 */
export declare type HistoryEvent = Message<"HistoryEvent"> & {
  /**
   * @generated from field: int32 eventId = 1;
   */
  eventId: number;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 2;
   */
  timestamp?: Timestamp | undefined;

  /**
   * @generated from oneof HistoryEvent.eventType
   */
  eventType: {
    /**
     * @generated from field: ExecutionStartedEvent executionStarted = 3;
     */
    value: ExecutionStartedEvent;
    case: "executionStarted";
  } | {
    /**
     * @generated from field: ExecutionCompletedEvent executionCompleted = 4;
     */
    value: ExecutionCompletedEvent;
    case: "executionCompleted";
  } | {
    /**
     * @generated from field: ExecutionTerminatedEvent executionTerminated = 5;
     */
    value: ExecutionTerminatedEvent;
    case: "executionTerminated";
  } | {
    /**
     * @generated from field: TaskScheduledEvent taskScheduled = 6;
     */
    value: TaskScheduledEvent;
    case: "taskScheduled";
  } | {
    /**
     * @generated from field: TaskCompletedEvent taskCompleted = 7;
     */
    value: TaskCompletedEvent;
    case: "taskCompleted";
  } | {
    /**
     * @generated from field: TaskFailedEvent taskFailed = 8;
     */
    value: TaskFailedEvent;
    case: "taskFailed";
  } | {
    /**
     * @generated from field: ChildWorkflowInstanceCreatedEvent childWorkflowInstanceCreated = 9;
     */
    value: ChildWorkflowInstanceCreatedEvent;
    case: "childWorkflowInstanceCreated";
  } | {
    /**
     * @generated from field: ChildWorkflowInstanceCompletedEvent childWorkflowInstanceCompleted = 10;
     */
    value: ChildWorkflowInstanceCompletedEvent;
    case: "childWorkflowInstanceCompleted";
  } | {
    /**
     * @generated from field: ChildWorkflowInstanceFailedEvent childWorkflowInstanceFailed = 11;
     */
    value: ChildWorkflowInstanceFailedEvent;
    case: "childWorkflowInstanceFailed";
  } | {
    /**
     * @generated from field: TimerCreatedEvent timerCreated = 12;
     */
    value: TimerCreatedEvent;
    case: "timerCreated";
  } | {
    /**
     * @generated from field: TimerFiredEvent timerFired = 13;
     */
    value: TimerFiredEvent;
    case: "timerFired";
  } | {
    /**
     * @generated from field: WorkflowStartedEvent workflowStarted = 14;
     */
    value: WorkflowStartedEvent;
    case: "workflowStarted";
  } | {
    /**
     * @generated from field: WorkflowCompletedEvent workflowCompleted = 15;
     */
    value: WorkflowCompletedEvent;
    case: "workflowCompleted";
  } | {
    /**
     * @generated from field: EventSentEvent eventSent = 16;
     */
    value: EventSentEvent;
    case: "eventSent";
  } | {
    /**
     * @generated from field: EventRaisedEvent eventRaised = 17;
     */
    value: EventRaisedEvent;
    case: "eventRaised";
  } | {
    /**
     * @generated from field: ContinueAsNewEvent continueAsNew = 20;
     */
    value: ContinueAsNewEvent;
    case: "continueAsNew";
  } | {
    /**
     * @generated from field: ExecutionSuspendedEvent executionSuspended = 21;
     */
    value: ExecutionSuspendedEvent;
    case: "executionSuspended";
  } | {
    /**
     * @generated from field: ExecutionResumedEvent executionResumed = 22;
     */
    value: ExecutionResumedEvent;
    case: "executionResumed";
  } | {
    /**
     * @generated from field: ExecutionStalledEvent executionStalled = 31;
     */
    value: ExecutionStalledEvent;
    case: "executionStalled";
  } | {
    /**
     * @generated from field: DetachedWorkflowInstanceCreatedEvent detachedWorkflowInstanceCreated = 32;
     */
    value: DetachedWorkflowInstanceCreatedEvent;
    case: "detachedWorkflowInstanceCreated";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: optional TaskRouter router = 30;
   */
  router?: TaskRouter | undefined;
};

/**
 * Describes the message HistoryEvent.
 * Use `create(HistoryEventSchema)` to create a new message.
 */
export declare const HistoryEventSchema: GenMessage<HistoryEvent>;

/**
 * A self-contained range of events produced by a single app, used when
 * history from multiple workflows is propagated to a downstream workflow
 * or activity. Each chunk owns the raw event bytes its producer signed;
 * receivers digest those bytes directly and decode them into typed
 * HistoryEvents on demand.
 *
 * @generated from message PropagatedHistoryChunk
 */
export declare type PropagatedHistoryChunk = Message<"PropagatedHistoryChunk"> & {
  /**
   * Raw deterministic bytes of each HistoryEvent in this chunk, in execution
   * order. The producer marshals each event once and signs over these exact
   * bytes; receivers digest them directly and never re-marshal, so chunk
   * verification is independent of protobuf marshaler-version stability
   * across producer and receiver. This mirrors the approach attestations use
   * for ioDigest: signed bytes travel verbatim end-to-end. The chunk's
   * length is len(rawEvents).
   *
   * @generated from field: repeated bytes rawEvents = 1;
   */
  rawEvents: Uint8Array[];

  /**
   * @generated from field: string appId = 2;
   */
  appId: string;

  /**
   * The workflow instance ID/name that produced the events in this chunk.
   *
   * @generated from field: string instanceId = 3;
   */
  instanceId: string;

  /**
   * @generated from field: string workflowName = 4;
   */
  workflowName: string;

  /**
   * Raw deterministic bytes of each HistorySignature message produced by the
   * chunk's app at dispatch time, covering rawEvents in order. Receivers
   * unmarshal these on demand to verify the chain. Raw bytes are required
   * because HistorySignature.previousSignatureDigest commits to the exact
   * persisted serialization; re-marshaling on the wire would break chain
   * linkage. See backend_service.proto: HistorySignature.
   *
   * @generated from field: repeated bytes rawSignatures = 5;
   */
  rawSignatures: Uint8Array[];

  /**
   * X.509 certificate chains of the chunk app's signing identities,
   * DER-concatenated leaf-first then intermediates (same encoding as
   * backend_service.proto: SigningCertificate.certificate). Each
   * HistorySignature in rawSignatures has a certificateIndex that indexes
   * into this list, scoped to the chunk's producer app. Raw bytes here avoid
   * a circular import on backend_service.proto's SigningCertificate type.
   *
   * @generated from field: repeated bytes signingCertChains = 6;
   */
  signingCertChains: Uint8Array[];
};

/**
 * Describes the message PropagatedHistoryChunk.
 * Use `create(PropagatedHistoryChunkSchema)` to create a new message.
 */
export declare const PropagatedHistoryChunkSchema: GenMessage<PropagatedHistoryChunk>;

/**
 * @generated from message PropagatedHistory
 */
export declare type PropagatedHistory = Message<"PropagatedHistory"> & {
  /**
   * The propagation scope that was used to produce this history.
   *
   * @generated from field: HistoryPropagationScope scope = 1;
   */
  scope: HistoryPropagationScope;

  /**
   * Per-app history chunks. Each chunk owns the raw event bytes its producer
   * signed (PropagatedHistoryChunk.rawEvents); receivers digest those bytes
   * directly and decode them into typed HistoryEvents on demand. Chunks are
   * ordered, non-overlapping, and together describe the full propagated
   * event sequence.
   *
   * @generated from field: repeated PropagatedHistoryChunk chunks = 2;
   */
  chunks: PropagatedHistoryChunk[];
};

/**
 * Describes the message PropagatedHistory.
 * Use `create(PropagatedHistorySchema)` to create a new message.
 */
export declare const PropagatedHistorySchema: GenMessage<PropagatedHistory>;

