// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file dapr/proto/durabletask/v1/orchestration.proto (syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file dapr/proto/durabletask/v1/orchestration.proto.
 */
export declare const file_dapr_proto_durabletask_v1_orchestration: GenFile;

/**
 * @generated from message TaskRouter
 */
export declare type TaskRouter = Message<"TaskRouter"> & {
  /**
   * @generated from field: string sourceAppID = 1;
   */
  sourceAppID: string;

  /**
   * @generated from field: optional string targetAppID = 2;
   */
  targetAppID?: string | undefined;

  /**
   * @generated from field: optional string targetAppNamespace = 3;
   */
  targetAppNamespace?: string | undefined;
};

/**
 * Describes the message TaskRouter.
 * Use `create(TaskRouterSchema)` to create a new message.
 */
export declare const TaskRouterSchema: GenMessage<TaskRouter>;

/**
 * @generated from message WorkflowVersion
 */
export declare type WorkflowVersion = Message<"WorkflowVersion"> & {
  /**
   * @generated from field: repeated string patches = 1;
   */
  patches: string[];

  /**
   * The name of the executed workflow
   *
   * @generated from field: optional string name = 2;
   */
  name?: string | undefined;
};

/**
 * Describes the message WorkflowVersion.
 * Use `create(WorkflowVersionSchema)` to create a new message.
 */
export declare const WorkflowVersionSchema: GenMessage<WorkflowVersion>;

/**
 * @generated from message WorkflowInstance
 */
export declare type WorkflowInstance = Message<"WorkflowInstance"> & {
  /**
   * @generated from field: string instanceId = 1;
   */
  instanceId: string;

  /**
   * @generated from field: google.protobuf.StringValue executionId = 2;
   */
  executionId?: string | undefined;
};

/**
 * Describes the message WorkflowInstance.
 * Use `create(WorkflowInstanceSchema)` to create a new message.
 */
export declare const WorkflowInstanceSchema: GenMessage<WorkflowInstance>;

/**
 * @generated from message TaskFailureDetails
 */
export declare type TaskFailureDetails = Message<"TaskFailureDetails"> & {
  /**
   * @generated from field: string errorType = 1;
   */
  errorType: string;

  /**
   * @generated from field: string errorMessage = 2;
   */
  errorMessage: string;

  /**
   * @generated from field: google.protobuf.StringValue stackTrace = 3;
   */
  stackTrace?: string | undefined;

  /**
   * @generated from field: TaskFailureDetails innerFailure = 4;
   */
  innerFailure?: TaskFailureDetails | undefined;

  /**
   * @generated from field: bool isNonRetriable = 5;
   */
  isNonRetriable: boolean;
};

/**
 * Describes the message TaskFailureDetails.
 * Use `create(TaskFailureDetailsSchema)` to create a new message.
 */
export declare const TaskFailureDetailsSchema: GenMessage<TaskFailureDetails>;

/**
 * @generated from message ParentInstanceInfo
 */
export declare type ParentInstanceInfo = Message<"ParentInstanceInfo"> & {
  /**
   * @generated from field: int32 taskScheduledId = 1;
   */
  taskScheduledId: number;

  /**
   * @generated from field: google.protobuf.StringValue name = 2;
   */
  name?: string | undefined;

  /**
   * @generated from field: google.protobuf.StringValue version = 3;
   */
  version?: string | undefined;

  /**
   * @generated from field: WorkflowInstance workflowInstance = 4;
   */
  workflowInstance?: WorkflowInstance | undefined;

  /**
   * @generated from field: optional string appID = 5;
   */
  appID?: string | undefined;

  /**
   * @generated from field: optional string appNamespace = 6;
   */
  appNamespace?: string | undefined;
};

/**
 * Describes the message ParentInstanceInfo.
 * Use `create(ParentInstanceInfoSchema)` to create a new message.
 */
export declare const ParentInstanceInfoSchema: GenMessage<ParentInstanceInfo>;

/**
 * RerunParentInstanceInfo is used to indicate that this workflow was
 * started as part of a rerun operation. Contains information about the parent
 * workflow instance which was rerun.
 *
 * @generated from message RerunParentInstanceInfo
 */
export declare type RerunParentInstanceInfo = Message<"RerunParentInstanceInfo"> & {
  /**
   * instanceID is the workflow instance ID this workflow has been
   * rerun from.
   *
   * @generated from field: string instanceID = 1;
   */
  instanceID: string;
};

/**
 * Describes the message RerunParentInstanceInfo.
 * Use `create(RerunParentInstanceInfoSchema)` to create a new message.
 */
export declare const RerunParentInstanceInfoSchema: GenMessage<RerunParentInstanceInfo>;

/**
 * RetryParentInstanceInfo correlates a child-workflow retry attempt with the
 * initial attempt that spawned it. When a child workflow is scheduled with a
 * retry policy, each retry executes as a separate child workflow instance with
 * its own auto-generated instance ID. This message provides an explicit,
 * first-class link back to the first attempt so consumers no longer need to
 * reconstruct the relationship from event ordering and timer origins.
 *
 * Semantics: the first attempt carries no RetryParentInstanceInfo. Retry
 * attempts (2nd onward) carry RetryParentInstanceInfo with instanceID set to
 * the first attempt's instance ID. Consumers group attempts by reading the
 * parent workflow's history; the group key is retryParentInstanceInfo.instanceID
 * when present, otherwise the event's own instanceId.
 *
 * @generated from message RetryParentInstanceInfo
 */
export declare type RetryParentInstanceInfo = Message<"RetryParentInstanceInfo"> & {
  /**
   * instanceID is the instance ID of the first attempt in this child-workflow
   * retry chain.
   *
   * @generated from field: string instanceID = 1;
   */
  instanceID: string;
};

/**
 * Describes the message RetryParentInstanceInfo.
 * Use `create(RetryParentInstanceInfoSchema)` to create a new message.
 */
export declare const RetryParentInstanceInfoSchema: GenMessage<RetryParentInstanceInfo>;

/**
 * @generated from message TraceContext
 */
export declare type TraceContext = Message<"TraceContext"> & {
  /**
   * @generated from field: string traceParent = 1;
   */
  traceParent: string;

  /**
   * @generated from field: string spanID = 2 [deprecated = true];
   * @deprecated
   */
  spanID: string;

  /**
   * @generated from field: google.protobuf.StringValue traceState = 3;
   */
  traceState?: string | undefined;
};

/**
 * Describes the message TraceContext.
 * Use `create(TraceContextSchema)` to create a new message.
 */
export declare const TraceContextSchema: GenMessage<TraceContext>;

/**
 * @generated from message WorkflowState
 */
export declare type WorkflowState = Message<"WorkflowState"> & {
  /**
   * @generated from field: string instanceId = 1;
   */
  instanceId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.StringValue version = 3;
   */
  version?: string | undefined;

  /**
   * @generated from field: OrchestrationStatus workflowStatus = 4;
   */
  workflowStatus: OrchestrationStatus;

  /**
   * @generated from field: google.protobuf.Timestamp scheduledStartTimestamp = 5;
   */
  scheduledStartTimestamp?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp createdTimestamp = 6;
   */
  createdTimestamp?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp lastUpdatedTimestamp = 7;
   */
  lastUpdatedTimestamp?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.StringValue input = 8;
   */
  input?: string | undefined;

  /**
   * @generated from field: google.protobuf.StringValue output = 9;
   */
  output?: string | undefined;

  /**
   * @generated from field: google.protobuf.StringValue customStatus = 10;
   */
  customStatus?: string | undefined;

  /**
   * @generated from field: TaskFailureDetails failureDetails = 11;
   */
  failureDetails?: TaskFailureDetails | undefined;

  /**
   * @generated from field: google.protobuf.StringValue executionId = 12;
   */
  executionId?: string | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp completedTimestamp = 13;
   */
  completedTimestamp?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.StringValue parentInstanceId = 14;
   */
  parentInstanceId?: string | undefined;

  /**
   * @generated from field: map<string, string> tags = 15;
   */
  tags: { [key: string]: string };

  /**
   * @generated from field: google.protobuf.StringValue parentAppId = 16;
   */
  parentAppId?: string | undefined;

  /**
   * @generated from field: optional google.protobuf.Timestamp startedAt = 17;
   */
  startedAt?: Timestamp | undefined;
};

/**
 * Describes the message WorkflowState.
 * Use `create(WorkflowStateSchema)` to create a new message.
 */
export declare const WorkflowStateSchema: GenMessage<WorkflowState>;

/**
 * @generated from enum StalledReason
 */
export enum StalledReason {
  /**
   * @generated from enum value: PATCH_MISMATCH = 0;
   */
  PATCH_MISMATCH = 0,

  /**
   * @generated from enum value: VERSION_NOT_AVAILABLE = 1;
   */
  VERSION_NOT_AVAILABLE = 1,

  /**
   * @generated from enum value: PAYLOAD_SIZE_EXCEEDED = 2;
   */
  PAYLOAD_SIZE_EXCEEDED = 2,
}

/**
 * Describes the enum StalledReason.
 */
export declare const StalledReasonSchema: GenEnum<StalledReason>;

/**
 * @generated from enum OrchestrationStatus
 */
export enum OrchestrationStatus {
  /**
   * @generated from enum value: ORCHESTRATION_STATUS_RUNNING = 0;
   */
  RUNNING = 0,

  /**
   * @generated from enum value: ORCHESTRATION_STATUS_COMPLETED = 1;
   */
  COMPLETED = 1,

  /**
   * @generated from enum value: ORCHESTRATION_STATUS_CONTINUED_AS_NEW = 2;
   */
  CONTINUED_AS_NEW = 2,

  /**
   * @generated from enum value: ORCHESTRATION_STATUS_FAILED = 3;
   */
  FAILED = 3,

  /**
   * @generated from enum value: ORCHESTRATION_STATUS_CANCELED = 4;
   */
  CANCELED = 4,

  /**
   * @generated from enum value: ORCHESTRATION_STATUS_TERMINATED = 5;
   */
  TERMINATED = 5,

  /**
   * @generated from enum value: ORCHESTRATION_STATUS_PENDING = 6;
   */
  PENDING = 6,

  /**
   * @generated from enum value: ORCHESTRATION_STATUS_SUSPENDED = 7;
   */
  SUSPENDED = 7,

  /**
   * @generated from enum value: ORCHESTRATION_STATUS_STALLED = 8;
   */
  STALLED = 8,
}

/**
 * Describes the enum OrchestrationStatus.
 */
export declare const OrchestrationStatusSchema: GenEnum<OrchestrationStatus>;

/**
 * HistoryPropagationScope controls how history is propagated to a child
 * workflow or activity
 *
 * @generated from enum HistoryPropagationScope
 */
export enum HistoryPropagationScope {
  /**
   * No propagation. This is the default for an unset/missing field; the
   * child receives no history from the caller.
   *
   * @generated from enum value: HISTORY_PROPAGATION_SCOPE_NONE = 0;
   */
  NONE = 0,

  /**
   * Propagate the caller's own history events only. The child does
   * not see any ancestral history (trust boundary).
   *
   * @generated from enum value: HISTORY_PROPAGATION_SCOPE_OWN_HISTORY = 1;
   */
  OWN_HISTORY = 1,

  /**
   * Propagate the caller's own history events AND the full ancestral
   * chain. Any propagated history this workflow received from its
   * parent is forwarded to the child.
   *
   * @generated from enum value: HISTORY_PROPAGATION_SCOPE_LINEAGE = 2;
   */
  LINEAGE = 2,
}

/**
 * Describes the enum HistoryPropagationScope.
 */
export declare const HistoryPropagationScopeSchema: GenEnum<HistoryPropagationScope>;

