//
//Copyright 2025 The Dapr Authors
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// @generated by protoc-gen-es v2.14.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file dapr/proto/durabletask/v1/runtime_state.proto (package durabletask.protos.backend.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { StalledReason } from "./orchestration_pb.js";
import type { ExecutionCompletedEvent, ExecutionStartedEvent, HistoryEvent, PropagatedHistory } from "./history_events_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file dapr/proto/durabletask/v1/runtime_state.proto.
 */
export declare const file_dapr_proto_durabletask_v1_runtime_state: GenFile;

/**
 * @generated from message durabletask.protos.backend.v1.RuntimeStateStalled
 */
export declare type RuntimeStateStalled = Message<"durabletask.protos.backend.v1.RuntimeStateStalled"> & {
  /**
   * @generated from field: StalledReason reason = 1;
   */
  reason: StalledReason;

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string | undefined;
};

/**
 * Describes the message durabletask.protos.backend.v1.RuntimeStateStalled.
 * Use `create(RuntimeStateStalledSchema)` to create a new message.
 */
export declare const RuntimeStateStalledSchema: GenMessage<RuntimeStateStalled>;

/**
 * WorkflowRuntimeState holds the current state for a workflow.
 *
 * @generated from message durabletask.protos.backend.v1.WorkflowRuntimeState
 */
export declare type WorkflowRuntimeState = Message<"durabletask.protos.backend.v1.WorkflowRuntimeState"> & {
  /**
   * @generated from field: string instanceId = 1;
   */
  instanceId: string;

  /**
   * @generated from field: repeated HistoryEvent newEvents = 2;
   */
  newEvents: HistoryEvent[];

  /**
   * @generated from field: repeated HistoryEvent oldEvents = 3;
   */
  oldEvents: HistoryEvent[];

  /**
   * @generated from field: repeated HistoryEvent pendingTasks = 4;
   */
  pendingTasks: HistoryEvent[];

  /**
   * @generated from field: repeated HistoryEvent pendingTimers = 5;
   */
  pendingTimers: HistoryEvent[];

  /**
   * @generated from field: repeated durabletask.protos.backend.v1.WorkflowRuntimeStateMessage pendingMessages = 6;
   */
  pendingMessages: WorkflowRuntimeStateMessage[];

  /**
   * @generated from field: ExecutionStartedEvent startEvent = 7;
   */
  startEvent?: ExecutionStartedEvent | undefined;

  /**
   * @generated from field: ExecutionCompletedEvent completedEvent = 8;
   */
  completedEvent?: ExecutionCompletedEvent | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp createdTime = 9;
   */
  createdTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp lastUpdatedTime = 10;
   */
  lastUpdatedTime?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp completedTime = 11;
   */
  completedTime?: Timestamp | undefined;

  /**
   * @generated from field: bool continuedAsNew = 12;
   */
  continuedAsNew: boolean;

  /**
   * @generated from field: bool isSuspended = 13;
   */
  isSuspended: boolean;

  /**
   * @generated from field: google.protobuf.StringValue customStatus = 14;
   */
  customStatus?: string | undefined;

  /**
   * @generated from field: optional durabletask.protos.backend.v1.RuntimeStateStalled stalled = 15;
   */
  stalled?: RuntimeStateStalled | undefined;
};

/**
 * Describes the message durabletask.protos.backend.v1.WorkflowRuntimeState.
 * Use `create(WorkflowRuntimeStateSchema)` to create a new message.
 */
export declare const WorkflowRuntimeStateSchema: GenMessage<WorkflowRuntimeState>;

/**
 * WorkflowRuntimeStateMessage holds a HistoryEvent payload and the target instance ID.
 *
 * @generated from message durabletask.protos.backend.v1.WorkflowRuntimeStateMessage
 */
export declare type WorkflowRuntimeStateMessage = Message<"durabletask.protos.backend.v1.WorkflowRuntimeStateMessage"> & {
  /**
   * @generated from field: HistoryEvent historyEvent = 1;
   */
  historyEvent?: HistoryEvent | undefined;

  /**
   * @generated from field: string targetInstanceId = 2;
   */
  targetInstanceId: string;

  /**
   * Propagated history to deliver to the child workflow.
   * This is a transport field used when creating child workflows with
   * history propagation enabled. It is NOT stored as part of any
   * workflow's history events.
   *
   * @generated from field: optional PropagatedHistory propagatedHistory = 3;
   */
  propagatedHistory?: PropagatedHistory | undefined;
};

/**
 * Describes the message durabletask.protos.backend.v1.WorkflowRuntimeStateMessage.
 * Use `create(WorkflowRuntimeStateMessageSchema)` to create a new message.
 */
export declare const WorkflowRuntimeStateMessageSchema: GenMessage<WorkflowRuntimeStateMessage>;

