/*
Copyright 2026 The Dapr Authors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import { ConversationToolCall } from "./ConversationMessage.type";

// breakdown of tokens used in the prompt
export type ConversationResultPromptTokensDetails = {
  audioTokens?: number;
  cachedTokens?: number;
};

// breakdown of tokens used in completion
export type ConversationResultCompletionTokensDetails = {
  acceptedPredictionTokens?: number;
  audioTokens?: number;
  reasoningTokens?: number;
  rejectedPredictionTokens?: number;
};

// token usage statistics for completion request
export type ConversationResultUsage = {
  completionTokens?: number;
  promptTokens?: number;
  totalTokens?: number;
  completionTokensDetails?: ConversationResultCompletionTokensDetails;
  promptTokensDetails?: ConversationResultPromptTokensDetails;
};

// chat completion message generated by the model
export type ConversationResultMessage = {
  content?: string;
  toolCalls?: ConversationToolCall[];
};

 
export type ConversationResultChoice = {
  finishReason?: string;
  index?: number;
  message?: ConversationResultMessage;
};

// result for a conversation input
export type ConversationResult = {
  choices?: ConversationResultChoice[];
  model?: string;
  usage?: ConversationResultUsage;
};

// response for the Conversation API
export type ConversationResponse = {
  contextId?: string;
  outputs?: ConversationResult[];
};
