/*
Copyright 2025 The Dapr Authors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/**
 * Content part of a conversation message.
 */
export interface ConversationMessageContent {
  text: string;
}

/**
 * A message from the developer role.
 */
export interface ConversationMessageOfDeveloper {
  role: "developer";
  name?: string;
  content: ConversationMessageContent[];
}

/**
 * A message from the system role.
 */
export interface ConversationMessageOfSystem {
  role: "system";
  name?: string;
  content: ConversationMessageContent[];
}

/**
 * A message from the user role.
 */
export interface ConversationMessageOfUser {
  role: "user";
  name?: string;
  content: ConversationMessageContent[];
}

/**
 * A tool call generated by the model.
 */
export interface ConversationToolCall {
  id?: string;
  function?: {
    name: string;
    arguments: string;
  };
}

/**
 * A message from the assistant role.
 */
export interface ConversationMessageOfAssistant {
  role: "assistant";
  name?: string;
  content: ConversationMessageContent[];
  toolCalls?: ConversationToolCall[];
}

/**
 * A message from a tool (tool result).
 */
export interface ConversationMessageOfTool {
  role: "tool";
  toolId?: string;
  name: string;
  content: ConversationMessageContent[];
}

/**
 * Union type for all possible conversation messages.
 */
export type ConversationMessage =
  | ConversationMessageOfDeveloper
  | ConversationMessageOfSystem
  | ConversationMessageOfUser
  | ConversationMessageOfAssistant
  | ConversationMessageOfTool;

/**
 * Input for the conversation containing messages.
 */
export interface ConversationInput {
  messages: ConversationMessage[];
  scrubPii?: boolean;
}

/**
 * A function tool that can be used during the conversation.
 */
export interface ConversationToolFunction {
  name: string;
  description?: string;
  parameters?: Record<string, unknown>;
}

/**
 * A tool available during the conversation.
 */
export interface ConversationTool {
  function: ConversationToolFunction;
}

/**
 * Options for the Alpha2 Conversation API.
 */
export interface ConversationOptions {
  /** The ID of an existing chat context */
  contextId?: string;
  /** Metadata key-value pairs */
  metadata?: Record<string, string>;
  /** Scrub PII data that comes back from the LLM */
  scrubPii?: boolean;
  /** Temperature for the LLM (0.0 to 2.0) */
  temperature?: number;
  /** Tools available to the LLM during the conversation */
  tools?: ConversationTool[];
  /** Controls which tool is called by the model (none, auto, required, or specific tool name) */
  toolChoice?: string;
  /** Duration for prompt cache retention (e.g. "5m", "1h") */
  promptCacheRetention?: string;
  /** Expected response format from the LLM */
  responseFormat?: Record<string, unknown>;
}

/**
 * A tool call in a result message.
 */
export interface ConversationResultToolCall {
  id?: string;
  function?: {
    name: string;
    arguments: string;
  };
}

/**
 * The message content within a result choice.
 */
export interface ConversationResultMessage {
  content: string;
  toolCalls?: ConversationResultToolCall[];
}

/**
 * A choice in the conversation result (inspired by OpenAI ChatCompletionChoice).
 */
export interface ConversationResultChoice {
  /** Reason the model stopped: "stop", "length", "tool_calls", "content_filter" */
  finishReason: string;
  /** Index of the choice */
  index: number;
  /** The message generated by the model */
  message?: ConversationResultMessage;
}

/**
 * A single conversation result (inspired by OpenAI ChatCompletion).
 */
export interface ConversationResult {
  choices: ConversationResultChoice[];
}

/**
 * Response from the Alpha2 Conversation API.
 */
export interface ConversationResponse {
  /** The context ID for continuing the conversation */
  contextId?: string;
  /** Array of results from the LLM */
  outputs: ConversationResult[];
}
