apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: config-store
spec:
  type: configuration.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
