// source: dapr/proto/internals/v1/service_invocation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var dapr_proto_common_v1_common_pb = require('../../../../dapr/proto/common/v1/common_pb.js');
goog.object.extend(proto, dapr_proto_common_v1_common_pb);
var dapr_proto_internals_v1_apiversion_pb = require('../../../../dapr/proto/internals/v1/apiversion_pb.js');
goog.object.extend(proto, dapr_proto_internals_v1_apiversion_pb);
var dapr_proto_internals_v1_status_pb = require('../../../../dapr/proto/internals/v1/status_pb.js');
goog.object.extend(proto, dapr_proto_internals_v1_status_pb);
goog.exportSymbol('proto.dapr.proto.internals.v1.Actor', null, global);
goog.exportSymbol('proto.dapr.proto.internals.v1.InternalInvokeRequest', null, global);
goog.exportSymbol('proto.dapr.proto.internals.v1.InternalInvokeRequestStream', null, global);
goog.exportSymbol('proto.dapr.proto.internals.v1.InternalInvokeResponse', null, global);
goog.exportSymbol('proto.dapr.proto.internals.v1.InternalInvokeResponseStream', null, global);
goog.exportSymbol('proto.dapr.proto.internals.v1.ListStringValue', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.internals.v1.Actor = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.internals.v1.Actor, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.internals.v1.Actor.displayName = 'proto.dapr.proto.internals.v1.Actor';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.internals.v1.InternalInvokeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.internals.v1.InternalInvokeRequest.displayName = 'proto.dapr.proto.internals.v1.InternalInvokeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.internals.v1.InternalInvokeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.internals.v1.InternalInvokeResponse.displayName = 'proto.dapr.proto.internals.v1.InternalInvokeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.internals.v1.InternalInvokeRequestStream, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.internals.v1.InternalInvokeRequestStream.displayName = 'proto.dapr.proto.internals.v1.InternalInvokeRequestStream';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.internals.v1.InternalInvokeResponseStream, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.internals.v1.InternalInvokeResponseStream.displayName = 'proto.dapr.proto.internals.v1.InternalInvokeResponseStream';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.internals.v1.ListStringValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dapr.proto.internals.v1.ListStringValue.repeatedFields_, null);
};
goog.inherits(proto.dapr.proto.internals.v1.ListStringValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.internals.v1.ListStringValue.displayName = 'proto.dapr.proto.internals.v1.ListStringValue';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.internals.v1.Actor.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.internals.v1.Actor.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.internals.v1.Actor} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.Actor.toObject = function(includeInstance, msg) {
  var f, obj = {
    actorType: jspb.Message.getFieldWithDefault(msg, 1, ""),
    actorId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.internals.v1.Actor}
 */
proto.dapr.proto.internals.v1.Actor.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.internals.v1.Actor;
  return proto.dapr.proto.internals.v1.Actor.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.internals.v1.Actor} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.internals.v1.Actor}
 */
proto.dapr.proto.internals.v1.Actor.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setActorType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setActorId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.internals.v1.Actor.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.internals.v1.Actor.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.internals.v1.Actor} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.Actor.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getActorType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getActorId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string actor_type = 1;
 * @return {string}
 */
proto.dapr.proto.internals.v1.Actor.prototype.getActorType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.internals.v1.Actor} returns this
 */
proto.dapr.proto.internals.v1.Actor.prototype.setActorType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string actor_id = 2;
 * @return {string}
 */
proto.dapr.proto.internals.v1.Actor.prototype.getActorId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.internals.v1.Actor} returns this
 */
proto.dapr.proto.internals.v1.Actor.prototype.setActorId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.internals.v1.InternalInvokeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ver: jspb.Message.getFieldWithDefault(msg, 1, 0),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, proto.dapr.proto.internals.v1.ListStringValue.toObject) : [],
    message: (f = msg.getMessage()) && dapr_proto_common_v1_common_pb.InvokeRequest.toObject(includeInstance, f),
    actor: (f = msg.getActor()) && proto.dapr.proto.internals.v1.Actor.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequest}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.internals.v1.InternalInvokeRequest;
  return proto.dapr.proto.internals.v1.InternalInvokeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequest}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.dapr.proto.internals.v1.APIVersion} */ (reader.readEnum());
      msg.setVer(value);
      break;
    case 2:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.dapr.proto.internals.v1.ListStringValue.deserializeBinaryFromReader, "", new proto.dapr.proto.internals.v1.ListStringValue());
         });
      break;
    case 3:
      var value = new dapr_proto_common_v1_common_pb.InvokeRequest;
      reader.readMessage(value,dapr_proto_common_v1_common_pb.InvokeRequest.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    case 4:
      var value = new proto.dapr.proto.internals.v1.Actor;
      reader.readMessage(value,proto.dapr.proto.internals.v1.Actor.deserializeBinaryFromReader);
      msg.setActor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.internals.v1.InternalInvokeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVer();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.dapr.proto.internals.v1.ListStringValue.serializeBinaryToWriter);
  }
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      dapr_proto_common_v1_common_pb.InvokeRequest.serializeBinaryToWriter
    );
  }
  f = message.getActor();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.dapr.proto.internals.v1.Actor.serializeBinaryToWriter
    );
  }
};


/**
 * optional APIVersion ver = 1;
 * @return {!proto.dapr.proto.internals.v1.APIVersion}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.getVer = function() {
  return /** @type {!proto.dapr.proto.internals.v1.APIVersion} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.dapr.proto.internals.v1.APIVersion} value
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequest} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.setVer = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * map<string, ListStringValue> metadata = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.dapr.proto.internals.v1.ListStringValue>}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.dapr.proto.internals.v1.ListStringValue>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.dapr.proto.internals.v1.ListStringValue));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequest} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;
};


/**
 * optional dapr.proto.common.v1.InvokeRequest message = 3;
 * @return {?proto.dapr.proto.common.v1.InvokeRequest}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.getMessage = function() {
  return /** @type{?proto.dapr.proto.common.v1.InvokeRequest} */ (
    jspb.Message.getWrapperField(this, dapr_proto_common_v1_common_pb.InvokeRequest, 3));
};


/**
 * @param {?proto.dapr.proto.common.v1.InvokeRequest|undefined} value
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequest} returns this
*/
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequest} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Actor actor = 4;
 * @return {?proto.dapr.proto.internals.v1.Actor}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.getActor = function() {
  return /** @type{?proto.dapr.proto.internals.v1.Actor} */ (
    jspb.Message.getWrapperField(this, proto.dapr.proto.internals.v1.Actor, 4));
};


/**
 * @param {?proto.dapr.proto.internals.v1.Actor|undefined} value
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequest} returns this
*/
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.setActor = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequest} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.clearActor = function() {
  return this.setActor(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequest.prototype.hasActor = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.internals.v1.InternalInvokeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && dapr_proto_internals_v1_status_pb.Status.toObject(includeInstance, f),
    headersMap: (f = msg.getHeadersMap()) ? f.toObject(includeInstance, proto.dapr.proto.internals.v1.ListStringValue.toObject) : [],
    trailersMap: (f = msg.getTrailersMap()) ? f.toObject(includeInstance, proto.dapr.proto.internals.v1.ListStringValue.toObject) : [],
    message: (f = msg.getMessage()) && dapr_proto_common_v1_common_pb.InvokeResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponse}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.internals.v1.InternalInvokeResponse;
  return proto.dapr.proto.internals.v1.InternalInvokeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponse}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new dapr_proto_internals_v1_status_pb.Status;
      reader.readMessage(value,dapr_proto_internals_v1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = msg.getHeadersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.dapr.proto.internals.v1.ListStringValue.deserializeBinaryFromReader, "", new proto.dapr.proto.internals.v1.ListStringValue());
         });
      break;
    case 3:
      var value = msg.getTrailersMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.dapr.proto.internals.v1.ListStringValue.deserializeBinaryFromReader, "", new proto.dapr.proto.internals.v1.ListStringValue());
         });
      break;
    case 4:
      var value = new dapr_proto_common_v1_common_pb.InvokeResponse;
      reader.readMessage(value,dapr_proto_common_v1_common_pb.InvokeResponse.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.internals.v1.InternalInvokeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      dapr_proto_internals_v1_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getHeadersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.dapr.proto.internals.v1.ListStringValue.serializeBinaryToWriter);
  }
  f = message.getTrailersMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.dapr.proto.internals.v1.ListStringValue.serializeBinaryToWriter);
  }
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      dapr_proto_common_v1_common_pb.InvokeResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional Status status = 1;
 * @return {?proto.dapr.proto.internals.v1.Status}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.getStatus = function() {
  return /** @type{?proto.dapr.proto.internals.v1.Status} */ (
    jspb.Message.getWrapperField(this, dapr_proto_internals_v1_status_pb.Status, 1));
};


/**
 * @param {?proto.dapr.proto.internals.v1.Status|undefined} value
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponse} returns this
*/
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponse} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * map<string, ListStringValue> headers = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.dapr.proto.internals.v1.ListStringValue>}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.getHeadersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.dapr.proto.internals.v1.ListStringValue>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.dapr.proto.internals.v1.ListStringValue));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponse} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.clearHeadersMap = function() {
  this.getHeadersMap().clear();
  return this;
};


/**
 * map<string, ListStringValue> trailers = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.dapr.proto.internals.v1.ListStringValue>}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.getTrailersMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.dapr.proto.internals.v1.ListStringValue>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.dapr.proto.internals.v1.ListStringValue));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponse} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.clearTrailersMap = function() {
  this.getTrailersMap().clear();
  return this;
};


/**
 * optional dapr.proto.common.v1.InvokeResponse message = 4;
 * @return {?proto.dapr.proto.common.v1.InvokeResponse}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.getMessage = function() {
  return /** @type{?proto.dapr.proto.common.v1.InvokeResponse} */ (
    jspb.Message.getWrapperField(this, dapr_proto_common_v1_common_pb.InvokeResponse, 4));
};


/**
 * @param {?proto.dapr.proto.common.v1.InvokeResponse|undefined} value
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponse} returns this
*/
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.setMessage = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponse} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponse.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.internals.v1.InternalInvokeRequestStream.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeRequestStream} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.toObject = function(includeInstance, msg) {
  var f, obj = {
    request: (f = msg.getRequest()) && proto.dapr.proto.internals.v1.InternalInvokeRequest.toObject(includeInstance, f),
    payload: (f = msg.getPayload()) && dapr_proto_common_v1_common_pb.StreamPayload.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequestStream}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.internals.v1.InternalInvokeRequestStream;
  return proto.dapr.proto.internals.v1.InternalInvokeRequestStream.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeRequestStream} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequestStream}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.dapr.proto.internals.v1.InternalInvokeRequest;
      reader.readMessage(value,proto.dapr.proto.internals.v1.InternalInvokeRequest.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    case 2:
      var value = new dapr_proto_common_v1_common_pb.StreamPayload;
      reader.readMessage(value,dapr_proto_common_v1_common_pb.StreamPayload.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.internals.v1.InternalInvokeRequestStream.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeRequestStream} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.dapr.proto.internals.v1.InternalInvokeRequest.serializeBinaryToWriter
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      dapr_proto_common_v1_common_pb.StreamPayload.serializeBinaryToWriter
    );
  }
};


/**
 * optional InternalInvokeRequest request = 1;
 * @return {?proto.dapr.proto.internals.v1.InternalInvokeRequest}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.getRequest = function() {
  return /** @type{?proto.dapr.proto.internals.v1.InternalInvokeRequest} */ (
    jspb.Message.getWrapperField(this, proto.dapr.proto.internals.v1.InternalInvokeRequest, 1));
};


/**
 * @param {?proto.dapr.proto.internals.v1.InternalInvokeRequest|undefined} value
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequestStream} returns this
*/
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.setRequest = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequestStream} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.clearRequest = function() {
  return this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional dapr.proto.common.v1.StreamPayload payload = 2;
 * @return {?proto.dapr.proto.common.v1.StreamPayload}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.getPayload = function() {
  return /** @type{?proto.dapr.proto.common.v1.StreamPayload} */ (
    jspb.Message.getWrapperField(this, dapr_proto_common_v1_common_pb.StreamPayload, 2));
};


/**
 * @param {?proto.dapr.proto.common.v1.StreamPayload|undefined} value
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequestStream} returns this
*/
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeRequestStream} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.internals.v1.InternalInvokeRequestStream.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.internals.v1.InternalInvokeResponseStream.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeResponseStream} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.toObject = function(includeInstance, msg) {
  var f, obj = {
    response: (f = msg.getResponse()) && proto.dapr.proto.internals.v1.InternalInvokeResponse.toObject(includeInstance, f),
    payload: (f = msg.getPayload()) && dapr_proto_common_v1_common_pb.StreamPayload.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponseStream}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.internals.v1.InternalInvokeResponseStream;
  return proto.dapr.proto.internals.v1.InternalInvokeResponseStream.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeResponseStream} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponseStream}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.dapr.proto.internals.v1.InternalInvokeResponse;
      reader.readMessage(value,proto.dapr.proto.internals.v1.InternalInvokeResponse.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    case 2:
      var value = new dapr_proto_common_v1_common_pb.StreamPayload;
      reader.readMessage(value,dapr_proto_common_v1_common_pb.StreamPayload.deserializeBinaryFromReader);
      msg.setPayload(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.internals.v1.InternalInvokeResponseStream.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.internals.v1.InternalInvokeResponseStream} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.dapr.proto.internals.v1.InternalInvokeResponse.serializeBinaryToWriter
    );
  }
  f = message.getPayload();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      dapr_proto_common_v1_common_pb.StreamPayload.serializeBinaryToWriter
    );
  }
};


/**
 * optional InternalInvokeResponse response = 1;
 * @return {?proto.dapr.proto.internals.v1.InternalInvokeResponse}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.getResponse = function() {
  return /** @type{?proto.dapr.proto.internals.v1.InternalInvokeResponse} */ (
    jspb.Message.getWrapperField(this, proto.dapr.proto.internals.v1.InternalInvokeResponse, 1));
};


/**
 * @param {?proto.dapr.proto.internals.v1.InternalInvokeResponse|undefined} value
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponseStream} returns this
*/
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.setResponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponseStream} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.clearResponse = function() {
  return this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional dapr.proto.common.v1.StreamPayload payload = 2;
 * @return {?proto.dapr.proto.common.v1.StreamPayload}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.getPayload = function() {
  return /** @type{?proto.dapr.proto.common.v1.StreamPayload} */ (
    jspb.Message.getWrapperField(this, dapr_proto_common_v1_common_pb.StreamPayload, 2));
};


/**
 * @param {?proto.dapr.proto.common.v1.StreamPayload|undefined} value
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponseStream} returns this
*/
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.setPayload = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.internals.v1.InternalInvokeResponseStream} returns this
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.clearPayload = function() {
  return this.setPayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.internals.v1.InternalInvokeResponseStream.prototype.hasPayload = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dapr.proto.internals.v1.ListStringValue.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.internals.v1.ListStringValue.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.internals.v1.ListStringValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.internals.v1.ListStringValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.ListStringValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    valuesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.internals.v1.ListStringValue}
 */
proto.dapr.proto.internals.v1.ListStringValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.internals.v1.ListStringValue;
  return proto.dapr.proto.internals.v1.ListStringValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.internals.v1.ListStringValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.internals.v1.ListStringValue}
 */
proto.dapr.proto.internals.v1.ListStringValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addValues(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.internals.v1.ListStringValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.internals.v1.ListStringValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.internals.v1.ListStringValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.internals.v1.ListStringValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValuesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string values = 1;
 * @return {!Array<string>}
 */
proto.dapr.proto.internals.v1.ListStringValue.prototype.getValuesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.dapr.proto.internals.v1.ListStringValue} returns this
 */
proto.dapr.proto.internals.v1.ListStringValue.prototype.setValuesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.dapr.proto.internals.v1.ListStringValue} returns this
 */
proto.dapr.proto.internals.v1.ListStringValue.prototype.addValues = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dapr.proto.internals.v1.ListStringValue} returns this
 */
proto.dapr.proto.internals.v1.ListStringValue.prototype.clearValuesList = function() {
  return this.setValuesList([]);
};


goog.object.extend(exports, proto.dapr.proto.internals.v1);
