/*
Copyright 2022 The Dapr Authors
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import GRPCClient from "./GRPCClient";
import Class from "../../../types/Class";
import { GRPCClientProxy as GRPCClientProxyImpl } from "./GRPCClientProxy";
import IClientProxy from "../../../interfaces/Client/IClientProxy";

/**
 * gRPC proxy wrapper for service-to-service invocation.
 *
 * Provides type-safe proxy creation for invoking remote services through the Dapr sidecar
 * using the gRPC protocol. Proxies automatically handle serialization, method routing,
 * and gRPC communication to the target service.
 *
 * @implements {IClientProxy}
 *
 * @internal
 */
export default class GRPCClientProxy implements IClientProxy {
  /**
   * Reference to the underlying gRPC client.
   */
  client: GRPCClient;

  /**
   * Creates a gRPC proxy wrapper.
   *
   * @param client - The gRPC client instance
   */
  constructor(client: GRPCClient) {
    this.client = client;
  }

  /**
   * Creates a type-safe proxy for service-to-service invocation.
   *
   * Returns a proxy object that implements the specified service class interface,
   * with methods that invoke the remote service through the Dapr sidecar.
   * Supports arbitrary service interfaces with automatic method routing.
   *
   * @typeParam T - The service interface type to proxy
   * @param cls - The service class/interface to proxy. Methods on the proxy will match this interface.
   * @param _clientOptions - Optional proxy configuration (currently unused)
   *
   * @returns Promise resolving to a proxy implementing service interface T
   *
   * @throws Rejects if proxy construction fails or gRPC connection is unavailable
   *
   * @example
   * ```typescript
   * // Define a service interface
   * class MyRemoteService {
   *   async greet(name: string): Promise<string> {
   *     // Implementation would be generated by proxy
   *   }
   * }
   *
   * // Create a proxy instance
   * const proxy = await client.proxy.create(MyRemoteService);
   *
   * // Call remote methods as if they were local
   * const result = await proxy.greet("World");
   * ```
   *
   * @see {@link HTTPClientProxy} for HTTP-based invocation (without proxy support)
   * @see {@link DaprClient.proxy} for unified API
   */
  async create<T>(cls: Class<T>, _clientOptions?: Record<string, unknown>): Promise<T> {
    const proxy = new GRPCClientProxyImpl<T>(cls, this.client);
    return proxy.build();
  }
}

