// source: dapr/proto/runtime/v1/pubsub.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var dapr_proto_runtime_v1_appcallback_pb = require('../../../../dapr/proto/runtime/v1/appcallback_pb.js');
goog.object.extend(proto, dapr_proto_runtime_v1_appcallback_pb);
goog.exportSymbol('proto.dapr.proto.runtime.v1.BulkPublishRequest', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.BulkPublishRequestEntry', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.BulkPublishResponse', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.PublishEventRequest', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.SubscribeTopicEventsRequestTypeCase', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.SubscribeTopicEventsResponseTypeCase', null, global);
goog.exportSymbol('proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.PublishEventRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.runtime.v1.PublishEventRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.PublishEventRequest.displayName = 'proto.dapr.proto.runtime.v1.PublishEventRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dapr.proto.runtime.v1.BulkPublishRequest.repeatedFields_, null);
};
goog.inherits(proto.dapr.proto.runtime.v1.BulkPublishRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.BulkPublishRequest.displayName = 'proto.dapr.proto.runtime.v1.BulkPublishRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.runtime.v1.BulkPublishRequestEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.displayName = 'proto.dapr.proto.runtime.v1.BulkPublishRequestEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dapr.proto.runtime.v1.BulkPublishResponse.repeatedFields_, null);
};
goog.inherits(proto.dapr.proto.runtime.v1.BulkPublishResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.BulkPublishResponse.displayName = 'proto.dapr.proto.runtime.v1.BulkPublishResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.displayName = 'proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.oneofGroups_);
};
goog.inherits(proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.displayName = 'proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.displayName = 'proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.displayName = 'proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.oneofGroups_);
};
goog.inherits(proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.displayName = 'proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.displayName = 'proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.PublishEventRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.PublishEventRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pubsubName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    topic: jspb.Message.getFieldWithDefault(msg, 2, ""),
    data: msg.getData_asB64(),
    dataContentType: jspb.Message.getFieldWithDefault(msg, 4, ""),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.PublishEventRequest}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.PublishEventRequest;
  return proto.dapr.proto.runtime.v1.PublishEventRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.PublishEventRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.PublishEventRequest}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPubsubName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDataContentType(value);
      break;
    case 5:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.PublishEventRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.PublishEventRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPubsubName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getDataContentType();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string pubsub_name = 1;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.getPubsubName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.PublishEventRequest} returns this
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.setPubsubName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string topic = 2;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.PublishEventRequest} returns this
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes data = 3;
 * @return {!(string|Uint8Array)}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.getData = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes data = 3;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.dapr.proto.runtime.v1.PublishEventRequest} returns this
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.setData = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional string data_content_type = 4;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.getDataContentType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.PublishEventRequest} returns this
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.setDataContentType = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * map<string, string> metadata = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.dapr.proto.runtime.v1.PublishEventRequest} returns this
 */
proto.dapr.proto.runtime.v1.PublishEventRequest.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.BulkPublishRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pubsubName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    topic: jspb.Message.getFieldWithDefault(msg, 2, ""),
    entriesList: jspb.Message.toObjectList(msg.getEntriesList(),
    proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.toObject, includeInstance),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequest}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.BulkPublishRequest;
  return proto.dapr.proto.runtime.v1.BulkPublishRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequest}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPubsubName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 3:
      var value = new proto.dapr.proto.runtime.v1.BulkPublishRequestEntry;
      reader.readMessage(value,proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.deserializeBinaryFromReader);
      msg.addEntries(value);
      break;
    case 4:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.BulkPublishRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPubsubName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEntriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.serializeBinaryToWriter
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string pubsub_name = 1;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.getPubsubName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequest} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.setPubsubName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string topic = 2;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequest} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated BulkPublishRequestEntry entries = 3;
 * @return {!Array<!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry>}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.getEntriesList = function() {
  return /** @type{!Array<!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.dapr.proto.runtime.v1.BulkPublishRequestEntry, 3));
};


/**
 * @param {!Array<!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry>} value
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequest} returns this
*/
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.setEntriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.addEntries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.dapr.proto.runtime.v1.BulkPublishRequestEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequest} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.clearEntriesList = function() {
  return this.setEntriesList([]);
};


/**
 * map<string, string> metadata = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequest} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishRequest.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    entryId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    event: msg.getEvent_asB64(),
    contentType: jspb.Message.getFieldWithDefault(msg, 3, ""),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.BulkPublishRequestEntry;
  return proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntryId(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEvent(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setContentType(value);
      break;
    case 4:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntryId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEvent_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getContentType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string entry_id = 1;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.getEntryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.setEntryId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes event = 2;
 * @return {!(string|Uint8Array)}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.getEvent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes event = 2;
 * This is a type-conversion wrapper around `getEvent()`
 * @return {string}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.getEvent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEvent()));
};


/**
 * optional bytes event = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEvent()`
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.getEvent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEvent()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.setEvent = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional string content_type = 3;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.getContentType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.setContentType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * map<string, string> metadata = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishRequestEntry} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishRequestEntry.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.BulkPublishResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    failedentriesList: jspb.Message.toObjectList(msg.getFailedentriesList(),
    proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishResponse}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.BulkPublishResponse;
  return proto.dapr.proto.runtime.v1.BulkPublishResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishResponse}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry;
      reader.readMessage(value,proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.deserializeBinaryFromReader);
      msg.addFailedentries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.BulkPublishResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFailedentriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.serializeBinaryToWriter
    );
  }
};


/**
 * repeated BulkPublishResponseFailedEntry failedEntries = 1;
 * @return {!Array<!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry>}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.prototype.getFailedentriesList = function() {
  return /** @type{!Array<!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry, 1));
};


/**
 * @param {!Array<!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry>} value
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishResponse} returns this
*/
proto.dapr.proto.runtime.v1.BulkPublishResponse.prototype.setFailedentriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.prototype.addFailedentries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishResponse} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishResponse.prototype.clearFailedentriesList = function() {
  return this.setFailedentriesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    entryId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    error: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry;
  return proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntryId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntryId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getError();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string entry_id = 1;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.prototype.getEntryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.prototype.setEntryId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string error = 2;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry} returns this
 */
proto.dapr.proto.runtime.v1.BulkPublishResponseFailedEntry.prototype.setError = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.SubscribeTopicEventsRequestTypeCase = {
  SUBSCRIBE_TOPIC_EVENTS_REQUEST_TYPE_NOT_SET: 0,
  INITIAL_REQUEST: 1,
  EVENT_PROCESSED: 2
};

/**
 * @return {proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.SubscribeTopicEventsRequestTypeCase}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.getSubscribeTopicEventsRequestTypeCase = function() {
  return /** @type {proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.SubscribeTopicEventsRequestTypeCase} */(jspb.Message.computeOneofCase(this, proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.toObject = function(includeInstance, msg) {
  var f, obj = {
    initialRequest: (f = msg.getInitialRequest()) && proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.toObject(includeInstance, f),
    eventProcessed: (f = msg.getEventProcessed()) && proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1;
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1;
      reader.readMessage(value,proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.deserializeBinaryFromReader);
      msg.setInitialRequest(value);
      break;
    case 2:
      var value = new proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1;
      reader.readMessage(value,proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.deserializeBinaryFromReader);
      msg.setEventProcessed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInitialRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.serializeBinaryToWriter
    );
  }
  f = message.getEventProcessed();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.serializeBinaryToWriter
    );
  }
};


/**
 * optional SubscribeTopicEventsRequestInitialAlpha1 initial_request = 1;
 * @return {?proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.getInitialRequest = function() {
  return /** @type{?proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1} */ (
    jspb.Message.getWrapperField(this, proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1, 1));
};


/**
 * @param {?proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1|undefined} value
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1} returns this
*/
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.setInitialRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.clearInitialRequest = function() {
  return this.setInitialRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.hasInitialRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SubscribeTopicEventsRequestProcessedAlpha1 event_processed = 2;
 * @return {?proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.getEventProcessed = function() {
  return /** @type{?proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1} */ (
    jspb.Message.getWrapperField(this, proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1, 2));
};


/**
 * @param {?proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1|undefined} value
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1} returns this
*/
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.setEventProcessed = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.clearEventProcessed = function() {
  return this.setEventProcessed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestAlpha1.prototype.hasEventProcessed = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.toObject = function(includeInstance, msg) {
  var f, obj = {
    pubsubName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    topic: jspb.Message.getFieldWithDefault(msg, 2, ""),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, undefined) : [],
    deadLetterTopic: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1;
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPubsubName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 3:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeadLetterTopic(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPubsubName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string pubsub_name = 1;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.getPubsubName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.setPubsubName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string topic = 2;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * map<string, string> metadata = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;};


/**
 * optional string dead_letter_topic = 4;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.getDeadLetterTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.setDeadLetterTopic = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.clearDeadLetterTopic = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestInitialAlpha1.prototype.hasDeadLetterTopic = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: (f = msg.getStatus()) && dapr_proto_runtime_v1_appcallback_pb.TopicEventResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1;
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new dapr_proto_runtime_v1_appcallback_pb.TopicEventResponse;
      reader.readMessage(value,dapr_proto_runtime_v1_appcallback_pb.TopicEventResponse.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      dapr_proto_runtime_v1_appcallback_pb.TopicEventResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TopicEventResponse status = 2;
 * @return {?proto.dapr.proto.runtime.v1.TopicEventResponse}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.prototype.getStatus = function() {
  return /** @type{?proto.dapr.proto.runtime.v1.TopicEventResponse} */ (
    jspb.Message.getWrapperField(this, dapr_proto_runtime_v1_appcallback_pb.TopicEventResponse, 2));
};


/**
 * @param {?proto.dapr.proto.runtime.v1.TopicEventResponse|undefined} value
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1} returns this
*/
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsRequestProcessedAlpha1.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.SubscribeTopicEventsResponseTypeCase = {
  SUBSCRIBE_TOPIC_EVENTS_RESPONSE_TYPE_NOT_SET: 0,
  INITIAL_RESPONSE: 1,
  EVENT_MESSAGE: 2
};

/**
 * @return {proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.SubscribeTopicEventsResponseTypeCase}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.getSubscribeTopicEventsResponseTypeCase = function() {
  return /** @type {proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.SubscribeTopicEventsResponseTypeCase} */(jspb.Message.computeOneofCase(this, proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.toObject = function(includeInstance, msg) {
  var f, obj = {
    initialResponse: (f = msg.getInitialResponse()) && proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.toObject(includeInstance, f),
    eventMessage: (f = msg.getEventMessage()) && dapr_proto_runtime_v1_appcallback_pb.TopicEventRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1;
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1;
      reader.readMessage(value,proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.deserializeBinaryFromReader);
      msg.setInitialResponse(value);
      break;
    case 2:
      var value = new dapr_proto_runtime_v1_appcallback_pb.TopicEventRequest;
      reader.readMessage(value,dapr_proto_runtime_v1_appcallback_pb.TopicEventRequest.deserializeBinaryFromReader);
      msg.setEventMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInitialResponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.serializeBinaryToWriter
    );
  }
  f = message.getEventMessage();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      dapr_proto_runtime_v1_appcallback_pb.TopicEventRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional SubscribeTopicEventsResponseInitialAlpha1 initial_response = 1;
 * @return {?proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.getInitialResponse = function() {
  return /** @type{?proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1} */ (
    jspb.Message.getWrapperField(this, proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1, 1));
};


/**
 * @param {?proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1|undefined} value
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1} returns this
*/
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.setInitialResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.clearInitialResponse = function() {
  return this.setInitialResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.hasInitialResponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TopicEventRequest event_message = 2;
 * @return {?proto.dapr.proto.runtime.v1.TopicEventRequest}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.getEventMessage = function() {
  return /** @type{?proto.dapr.proto.runtime.v1.TopicEventRequest} */ (
    jspb.Message.getWrapperField(this, dapr_proto_runtime_v1_appcallback_pb.TopicEventRequest, 2));
};


/**
 * @param {?proto.dapr.proto.runtime.v1.TopicEventRequest|undefined} value
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1} returns this
*/
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.setEventMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1} returns this
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.clearEventMessage = function() {
  return this.setEventMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseAlpha1.prototype.hasEventMessage = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.prototype.toObject = function(opt_includeInstance) {
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1;
  return proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dapr.proto.runtime.v1.SubscribeTopicEventsResponseInitialAlpha1.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.dapr.proto.runtime.v1);
